service:
  name: ${file(custom.yml):variables.serviceName}

package:
  exclude:
    - test/**

plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs12.x
  region: ${file(custom.yml):variables.region}
  stage: ${file(custom.yml):variables.stage}


functions:
  watcher:
    ${file(functions/watcher/watcher.yml)}

  activateOrDeactivateWatcher:
    ${file(functions/activateOrDeactivateWatcher/activateOrDeactivateWatcher.yml)}

resources:
  ${file(Resources.yml)}
